#!/usr/bin/env node

/**
 * mind-ontology emit — compile static per-tool artifacts from .agentctx/.
 *
 * Implements ADL W3 of the Workbench v1 design packet against the normative
 * specs:
 *   - docs/workbench-w1-emit-target-spec.md (targets, profiles, header,
 *     determinism, drift classes)
 *   - docs/workbench-w2-cli-spec.md (flags, streams, exit codes, JSON shapes)
 *
 * Determinism invariant (W1 §7): emitted bytes are a pure function of
 * (canonicalized included source bytes, target id, profile, emit_version).
 * No timestamps, no machine identity, no locale-dependent ordering, no
 * randomness, no network or model calls anywhere in this module.
 */

import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  SAFETY_TAGS,
  SOURCE_FILES,
  parseMarkdownBlocks,
  readAgentctx,
  validateAgentctxSources,
} from "./compile.mjs";

// 2: cq.md exempted from the safety sweep (W4 operator ruling, W1 §3) —
// payloads emitted under version 1 no longer match and re-flag as STALE.
export const EMIT_VERSION = 2;

// W4 operator ruling (W1 §3): competency questions are questions, not
// executable constraints — a #safety tag on a CQ marks its topic (the CQ
// schema's required safety question), not an enforceable rule. Sweeping an
// unanswered question into the Constraints section would put a
// non-instruction into an instruction file, so cq.md never participates in
// the safety sweep. The live MCP path owns CQ surfacing.
export const SWEEP_EXEMPT_FILES = new Set(["cq.md"]);

// Normative target registry (W1 §2). Ids are stable forever; the registry-sync
// guard test asserts this constant matches the W1 spec table. Only `v1: true`
// targets are emittable today; the fast-follow rows are registered so their
// ids and artifact paths stay reserved.
export const EMIT_TARGETS = {
  "agents-md": { path: "AGENTS.md", title: "# AGENTS.md", v1: true },
  "claude-md": { path: "CLAUDE.md", title: "# CLAUDE.md", v1: true },
  cursor: { path: ".cursor/rules/mind-ontology.mdc", title: null, v1: false },
  "paste-block": { path: "mind-ontology-paste-block.md", title: null, v1: false },
};

export const V1_TARGET_IDS = Object.keys(EMIT_TARGETS).filter(
  (id) => EMIT_TARGETS[id].v1,
);

// Profiles are fixed engine constants (W1 §3; W2 §12: no profile editing) so
// --check can always recompile from the header's recorded profile name.
export const PROFILES = {
  default: {
    "constraints.md": "all",
    "identity.md": "all",
    "direction.md": "all",
    "projects.md": "none",
    "decisions.md": "none",
    "architecture.md": "none",
    "agent-roles.md": "all",
    "glossary.md": "none",
    "cq.md": "none",
  },
  full: Object.fromEntries(SOURCE_FILES.map((file) => [file, "all"])),
};

// Generated `##` section per source file. Section order is always
// SOURCE_FILES order (W1 §3); under the default profile that yields exactly
// the Constraints -> Identity -> Direction -> Agent roles order W1 §4 lists.
export const SECTION_TITLES = {
  "constraints.md": "Constraints",
  "identity.md": "Identity",
  "direction.md": "Direction",
  "projects.md": "Projects",
  "decisions.md": "Decisions",
  "architecture.md": "Architecture",
  "agent-roles.md": "Agent roles",
  "glossary.md": "Glossary",
  "cq.md": "Competency questions",
};

export const PAYLOAD_LINE_BUDGET = 400;

export const REQUIRED_HEADER_KEYS = [
  "target",
  "profile",
  "emit_version",
  "source",
  "source_digest",
  "content_digest",
  "note",
];

const HEADER_OPEN = "<!-- mind-ontology:emit";
const HEADER_CLOSE = "-->";
// ASCII only (W1 §6) so the header survives naive encoding round-trips.
const HEADER_NOTE =
  "GENERATED FILE - do not hand-edit. Edit .agentctx/ and re-run: mind-ontology emit";

// Per-target frame text (W1 §4-5). The payload blocks are byte-identical
// across targets (W1 principle 3); only these frame pieces differ. The
// CLAUDE.md notice carries the ratified W2 §8(c) amendment, shipped in the
// first golden so it never costs an emit_version bump.
const FRAMES = {
  "agents-md": {
    notice: [
      "> Generated by `mind-ontology emit` from `.agentctx/` — **do not hand-edit.**",
      "> Edit the source files and re-run `mind-ontology emit`. Agents with MCP",
      "> access get richer, task-scoped context from the live `get_context` tool.",
    ],
    footer: [
      "---",
      "*Source: `.agentctx/` · refresh: `mind-ontology emit` · verify: `mind-ontology emit --check`*",
    ],
  },
  "claude-md": {
    notice: [
      "> Generated by `mind-ontology emit` from `.agentctx/` — **do not hand-edit.**",
      "> Claude Code reads this file as project memory. Edit the source files and",
      "> re-run `mind-ontology emit`. Agents get richer, task-scoped context from",
      "> the live `agentctx` MCP server (`get_context` / `list_constraints`).",
      "> If your tooling also loads `AGENTS.md`, the two files carry identical",
      "> payloads — keep whichever your tools read and re-emit only that target.",
    ],
    footer: [
      "---",
      "*Source: `.agentctx/` · refresh: `mind-ontology emit` · verify: `mind-ontology emit --check`*",
      "*Per-user overrides belong in `CLAUDE.local.md` or user memory, not in this generated file.*",
    ],
  },
};

// W1 §7 canonicalization: strip a leading UTF-8 BOM, normalize CRLF -> LF,
// nothing else. Applied everywhere bytes are parsed, hashed, or compared.
export function canonicalize(text) {
  return String(text).replace(/^\uFEFF/, "").replace(/\r\n/g, "\n");
}

export function sha256(text) {
  return `sha256:${createHash("sha256").update(text, "utf8").digest("hex")}`;
}

function isSafetyBlock(block) {
  return block.tags.some((tag) => SAFETY_TAGS.has(tag));
}

function renderBlock(block) {
  // W1 §4 block rendering, identical across targets: heading title with tags
  // stripped, HTML provenance comment naming the true source file, body
  // verbatim. Source-level ## blocks render as ### so they nest under the
  // generated ## sections.
  const heading = `### ${block.title} <!-- (from .agentctx/${block.file}) -->`;
  return block.body ? `${heading}\n${block.body}` : heading;
}

// Canonical source-block text a block-manifest entry digests: the parsed
// block's raw heading and trimmed body, exactly the fields parseMarkdownBlocks
// produced from already-canonicalized source bytes. Deterministic by
// construction (no time, randomness, absolute path, or locale input), so the
// digest is a pure function of the source block's content — the same
// determinism contract the artifact bytes obey (W1 §7).
function blockSourceCanonical(block) {
  if (!block.heading) return block.body;
  return block.body ? `${block.heading}\n${block.body}` : block.heading;
}

/**
 * One block-manifest entry (Phase 1 provenance core): the traceability record
 * for a single emitted block. `source_file` is the block's TRUE origin file
 * (preserved across the safety sweep), `source_block_index` its position
 * within that source file, `source_block_digest` a content fingerprint of the
 * source block, `rendered_digest` the fingerprint of the emitted text,
 * `emitted_index` its position in the emitted block sequence, `section` the
 * generated section it renders under, and `forced` whether the safety sweep
 * pulled it into Constraints from an excluded file.
 *
 * Pure: derived from the same `renderBlock` primitive and the parsed block,
 * with no I/O. The manifest is computed alongside the artifact but never mixed
 * into the artifact bytes (backward-compat / determinism).
 */
function buildBlockManifestEntry(block, renderedText, { emittedIndex, section, forced }) {
  return {
    source_file: block.file,
    source_block_index: block.index,
    source_block_digest: sha256(blockSourceCanonical(block)),
    rendered_digest: sha256(renderedText),
    emitted_index: emittedIndex,
    section,
    forced,
  };
}

/**
 * Build one target artifact entirely in memory.
 * Returns { target, path, profile, payload, artifact, sourceDigest,
 *           contentDigest, payloadLines, lineContributions, blockManifest }.
 * `blockManifest` is an in-memory provenance array (one entry per emitted
 * block); it is NOT serialized into `artifact`/`payload` and does not affect
 * the emitted bytes.
 */
export function buildArtifact({ sources, target, profile = "default" }) {
  const spec = EMIT_TARGETS[target];
  if (!spec || !spec.v1) {
    throw new Error(
      `--target must be one of ${V1_TARGET_IDS.map((id) => `"${id}"`).join(", ")}, got: ${target}`,
    );
  }
  const rules = PROFILES[profile];
  if (!rules) {
    throw new Error(`Unknown emit profile: ${profile}`);
  }

  const canonical = {};
  const blocksByFile = {};
  for (const file of SOURCE_FILES) {
    canonical[file] = canonicalize(sources[file] ?? "");
    blocksByFile[file] = parseMarkdownBlocks(canonical[file], file);
  }

  // Safety sweep (W1 principle 4): safety-tagged blocks in excluded files are
  // forced into the Constraints section. A block selected by its own file's
  // rule is never re-appended. cq.md is exempt (SWEEP_EXEMPT_FILES).
  const forcedBlocks = [];
  const forcedFiles = new Set();
  for (const file of SOURCE_FILES) {
    if (rules[file] !== "none" || SWEEP_EXEMPT_FILES.has(file)) continue;
    for (const block of blocksByFile[file]) {
      if (isSafetyBlock(block)) {
        forcedBlocks.push(block);
        forcedFiles.add(file);
      }
    }
  }

  // Sections in SOURCE_FILES order; a section with zero blocks is omitted
  // entirely, heading included (W1 §4 empty-section rule). The block manifest
  // is accumulated in lock-step with the rendered blocks so emitted_index and
  // ordering are guaranteed consistent with the artifact bytes; it never feeds
  // back into `sections`/`payload`.
  const sections = [];
  const blockManifest = [];
  const lineContributions = new Map();
  const countLines = (file, text) => {
    lineContributions.set(
      file,
      (lineContributions.get(file) ?? 0) + text.split("\n").length,
    );
  };
  for (const file of SOURCE_FILES) {
    if (rules[file] === "none") continue;
    const nativeCount = blocksByFile[file].length;
    const blocks = [...blocksByFile[file]];
    if (file === "constraints.md") blocks.push(...forcedBlocks);
    if (blocks.length === 0) continue;
    const rendered = blocks.map((block, i) => {
      const text = renderBlock(block);
      countLines(block.file, text);
      // A constraints.md slot past the native blocks is a safety-forced block
      // swept in from an excluded file (W1 principle 4).
      const forced = file === "constraints.md" && i >= nativeCount;
      blockManifest.push(
        buildBlockManifestEntry(block, text, {
          emittedIndex: blockManifest.length,
          section: SECTION_TITLES[file],
          forced,
        }),
      );
      return text;
    });
    sections.push(`## ${SECTION_TITLES[file]}\n\n${rendered.join("\n\n")}`);
  }

  const frame = FRAMES[target];
  const payload =
    [spec.title, frame.notice.join("\n"), ...sections, frame.footer.join("\n")].join(
      "\n\n",
    ) + "\n";

  // source_digest (W1 §6): fingerprint of the inputs over every
  // profile-included file, in SOURCE_FILES order, plus the one asymmetry:
  // excluded files that currently contribute >=1 safety-forced block are
  // digested too, so edits to them re-flag the artifact.
  const digestParts = [];
  for (const file of SOURCE_FILES) {
    if (rules[file] === "none" && !forcedFiles.has(file)) continue;
    digestParts.push(`${file}\n${canonical[file]}\0`);
  }
  const sourceDigest = sha256(digestParts.join(""));
  const contentDigest = sha256(payload);

  const header = [
    HEADER_OPEN,
    `target: ${target}`,
    `profile: ${profile}`,
    `emit_version: ${EMIT_VERSION}`,
    "source: .agentctx/",
    `source_digest: ${sourceDigest}`,
    `content_digest: ${contentDigest}`,
    `note: ${HEADER_NOTE}`,
    HEADER_CLOSE,
  ].join("\n");

  const payloadLines = payload.split("\n").length - 1; // newline-terminated lines

  return {
    target,
    path: spec.path,
    profile,
    payload,
    artifact: `${header}\n${payload}`,
    sourceDigest,
    contentDigest,
    payloadLines,
    lineContributions,
    blockManifest,
  };
}

/**
 * Parse a generated-file header (W1 §6) from canonicalized artifact content.
 * Returns { header, payload } or null when the content is not a managed
 * artifact (no header block, unparseable line, or missing a required key).
 * Unknown keys are ignored (forward compatibility).
 */
export function parseEmitHeader(content) {
  const lines = String(content).split("\n");
  if (lines[0] !== HEADER_OPEN) return null;
  const header = {};
  let closeIndex = -1;
  for (let i = 1; i < lines.length; i += 1) {
    if (lines[i] === HEADER_CLOSE) {
      closeIndex = i;
      break;
    }
    const m = lines[i].match(/^([A-Za-z0-9_-]+): (.*)$/);
    if (!m) return null;
    header[m[1]] = m[2];
  }
  if (closeIndex === -1) return null;
  for (const key of REQUIRED_HEADER_KEYS) {
    if (!(key in header)) return null;
  }
  return { header, payload: lines.slice(closeIndex + 1).join("\n") };
}

// Operator-guidance detail sentences (W1 §8 per-class table; wording locked
// here, mirrored in docs/cli-errors.md, and asserted by the check matrix
// guard test).
export function detailFor(status, target, path) {
  switch (status) {
    case "missing":
      return `artifact has never been emitted (or was deleted); run: mind-ontology emit --target ${target}`;
    case "unmanaged":
      return `file exists but is not managed by emit; emit will not touch it without --force. Move hand-written content into .agentctx/ sources, then run: mind-ontology emit --force --target ${target}`;
    case "hand-edited":
      return `file was edited after generation; hand edits will be lost on re-emit. Port the edits into .agentctx/ sources, then re-emit. Diff hint: git diff ${path}`;
    case "stale":
      return `.agentctx/ changed (or emit_version bumped) since last emit; run: mind-ontology emit --target ${target}`;
    default:
      return null;
  }
}

/**
 * Classify one target (W1 §8): mutually exclusive classes, checked in order
 * MISSING -> UNMANAGED -> HAND-EDITED -> STALE -> OK. The hand-edit check
 * runs before staleness so the artifact disagreeing with itself is reported
 * independently of whether sources also moved.
 */
export function classifyTarget({ cwd, target, sources }) {
  const spec = EMIT_TARGETS[target];
  const path = resolve(cwd, spec.path);

  if (!existsSync(path)) {
    return {
      target,
      path: spec.path,
      status: "missing",
      detail: detailFor("missing", target, spec.path),
    };
  }

  const content = canonicalize(readFileSync(path, "utf8"));
  const parsed = parseEmitHeader(content);
  if (!parsed) {
    return {
      target,
      path: spec.path,
      status: "unmanaged",
      detail: detailFor("unmanaged", target, spec.path),
    };
  }

  // Carry the RECORDED header fields (target + profile, as written on disk) on
  // every header-present result. These can diverge from the requested `target`
  // / current generator (e.g. a header recording `target: cursor`), so both
  // explain and reconcile must judge reproducibility from these, not from the
  // requested target — single source of truth, no fork.
  const recorded = {
    recordedTarget: parsed.header.target,
    recordedProfile: parsed.header.profile,
  };

  if (sha256(parsed.payload) !== parsed.header.content_digest) {
    return {
      target,
      path: spec.path,
      status: "hand-edited",
      detail: detailFor("hand-edited", target, spec.path),
      profile: parsed.header.profile,
      ...recorded,
    };
  }

  const stale = {
    target,
    path: spec.path,
    status: "stale",
    detail: detailFor("stale", target, spec.path),
    profile: parsed.header.profile,
    ...recorded,
  };
  if (parsed.header.emit_version !== String(EMIT_VERSION)) return stale;
  // A header naming an unknown target or profile cannot be reproduced by the
  // current generator; re-emitting (which records current names) resolves it.
  if (!EMIT_TARGETS[parsed.header.target]?.v1 || !PROFILES[parsed.header.profile]) {
    return stale;
  }

  const expected = buildArtifact({
    sources,
    target: parsed.header.target,
    profile: parsed.header.profile,
  });
  if (expected.artifact !== content) return stale;

  return {
    target,
    path: spec.path,
    status: "ok",
    detail: null,
    profile: parsed.header.profile,
    ...recorded,
  };
}

/**
 * Drift explanation for one target (read-only; W2 §13 item 15). Reuses the
 * SAME primitives the classifier uses (parseEmitHeader, sha256, buildArtifact)
 * to surface WHY a target landed in its class and WHAT a reconcile would do —
 * never re-classifying and never writing. Driven by an already-computed
 * `result` from classifyTarget so the two can never disagree.
 *
 * Block-level provenance note: the artifact header records only file-level
 * digests (source_digest over included files, content_digest over the whole
 * payload), with no per-block manifest, so wouldWritePaths and reconcileCommand
 * are necessarily file-level (the single artifact path), not block-level.
 */
export function explainTarget({ cwd, target, sources, result }) {
  const spec = EMIT_TARGETS[target];
  const path = resolve(cwd, spec.path);
  const exists = existsSync(path);

  let parsed = null;
  if (exists) {
    parsed = parseEmitHeader(canonicalize(readFileSync(path, "utf8")));
  }
  const headerPresent = parsed !== null;
  const managed = headerPresent;

  // The profile a reconcile would recompile against: the one recorded in a
  // managed header, else the default profile a fresh emit uses.
  const expectedProfile = headerPresent ? parsed.header.profile : "default";

  let payloadDigestMatchesHeader = null;
  let emitVersionMatches = null;
  let sourceDigestMatchesCurrent = null;
  if (headerPresent) {
    payloadDigestMatchesHeader = sha256(parsed.payload) === parsed.header.content_digest;
    emitVersionMatches = parsed.header.emit_version === String(EMIT_VERSION);
    // Recompute the source fingerprint the current sources would produce under
    // the header's recorded profile and compare it to the header's record. A
    // reproducible profile is required to rebuild; otherwise the comparison is
    // undefined (null), mirroring the classifier treating it as stale.
    if (EMIT_TARGETS[parsed.header.target]?.v1 && PROFILES[parsed.header.profile]) {
      const expected = buildArtifact({
        sources,
        target: parsed.header.target,
        profile: parsed.header.profile,
      });
      sourceDigestMatchesCurrent = expected.sourceDigest === parsed.header.source_digest;
    }
  }

  // A STALE artifact is only safe to auto-reconcile when its RECORDED
  // target/profile is still reproducible — judged from the threaded recorded
  // fields, the SAME test `--reconcile` applies (single source of truth). An
  // unreproducible STALE (header records an unknown profile / non-v1 target) is
  // one reconcile REFUSES, so explain must not advertise --reconcile for it.
  const staleReproducible = result.status === "stale" && staleIsReproducible(result);

  // The command a user runs to fix this target, by class:
  //   MISSING / reproducible STALE -> safe to auto-reconcile. `emit --reconcile`
  //     re-emits respecting the recorded profile, so a `full` artifact stays
  //     `full` (it never silently degrades to default).
  //   unreproducible STALE         -> reconcile refuses; re-emit explicitly with
  //     a known profile.
  //   UNMANAGED                    -> needs --force (headerless file).
  //   HAND-EDITED                  -> port the edit into .agentctx/, then emit.
  //   OK                           -> nothing to reconcile; plain emit refreshes.
  const reconcileCommand =
    result.status === "missing" || staleReproducible
      ? `mind-ontology emit --reconcile --target ${target}`
      : result.status === "unmanaged"
        ? `mind-ontology emit --force --target ${target}`
        : `mind-ontology emit --target ${target}`;

  // A reconcile rewrites exactly this target's artifact. OK needs no reconcile,
  // so nothing would be written.
  const wouldWritePaths = result.status === "ok" ? [] : [spec.path];

  return {
    status: result.status,
    managed,
    headerPresent,
    payloadDigestMatchesHeader,
    sourceDigestMatchesCurrent,
    emitVersionMatches,
    expectedProfile,
    reconcileCommand,
    wouldWritePaths,
  };
}

// Human-readable explanation sentence(s) for the text surface (W2 §13 item
// 15): why this class, and what a reconcile would involve. Keyed by status so
// the wording stays in lock-step with the classifier.
export function explainText(result, explain) {
  switch (result.status) {
    case "missing":
      return `why: no artifact on disk (header absent). A reconcile would emit it, writing ${explain.wouldWritePaths.join(", ")}: ${explain.reconcileCommand}`;
    case "unmanaged":
      return `why: file exists but has no emit header, so emit will not claim it. Move the hand-written content into .agentctx/ sources, then reconcile (writes ${explain.wouldWritePaths.join(", ")}): ${explain.reconcileCommand}`;
    case "hand-edited":
      return `why: the payload no longer matches the header's content_digest (edited after generation). Re-emit overwrites the file, so move the hand-edit into the .agentctx/ source first, then re-emit (writes ${explain.wouldWritePaths.join(", ")}): ${explain.reconcileCommand}`;
    case "stale": {
      // An unreproducible STALE cannot be auto-reconciled (reconcile refuses
      // it); explain must say so and point at the manual re-emit, not advertise
      // --reconcile. The reproducible reasons keep the auto-reconcile wording.
      if (!staleIsReproducible(result)) {
        return `why: the recorded target/profile is no longer reproducible, so this CANNOT be auto-reconciled; re-emit it explicitly with a known profile (writes ${explain.wouldWritePaths.join(", ")}): ${explain.reconcileCommand}`;
      }
      const reason = explain.emitVersionMatches === false
        ? "emit_version bumped since last emit"
        : ".agentctx/ sources changed since last emit";
      return `why: ${reason} (profile ${explain.expectedProfile}). A reconcile re-emits it, writing ${explain.wouldWritePaths.join(", ")}: ${explain.reconcileCommand}`;
    }
    default:
      return `why: payload and source digests both match the header under profile ${explain.expectedProfile}; nothing to reconcile.`;
  }
}

// ---------------------------------------------------------------------------
// Block-level reconcile — read-only drift planner (lane 4, Phase 1)
//
// All pure (string in, data out): no I/O, no writes. These let a caller see
// WHICH emitted blocks drifted, as the read-only foundation for an opt-in
// block-level reconcile whose safety is proven by a full-artifact byte guard
// (the surgical patch is the mechanism; byte-equality with a full re-emit is
// the proof). Nothing here changes the artifact bytes or the existing surfaces.
// ---------------------------------------------------------------------------

// A rendered block heading in an emitted payload: '### <title> <!-- (from
// .agentctx/<file>) -->'. The trailing provenance comment is renderBlock's
// signature (W1 §4) and the reliable anchor for an emitted block start — far
// more robust than a blank line, since a block body may contain blank lines.
const EMITTED_BLOCK_HEADING = /^### .* <!-- \(from \.agentctx\/(.+?)\) -->$/;

/**
 * Parse an emitted artifact payload (the bytes AFTER the header terminator)
 * into its emitted block spans, in document order. Each span is one rendered
 * block: { emittedIndex, sourceFile, renderedText, renderedDigest, start, end }.
 * A block runs from its heading line to the next structural marker (another
 * block heading, a generated '## ' section heading, or the '---' footer); the
 * trailing '\n\n' join blank line is stripped, so renderedText is exactly
 * renderBlock's output and sha256(renderedText) reproduces the manifest's
 * rendered_digest. `start`/`end` are char offsets into `payload` such that
 * payload.slice(start, end) === renderedText (used by the patch primitive to
 * splice a single block in place). Pure.
 */
export function parseEmittedBlockSpans(payload) {
  const text = String(payload);
  const lines = text.split("\n");
  // Char offset of the start of each line in `text`.
  const lineStart = new Array(lines.length);
  let acc = 0;
  for (let k = 0; k < lines.length; k += 1) {
    lineStart[k] = acc;
    acc += lines[k].length + 1; // +1 for the '\n' join
  }

  const spans = [];
  let i = 0;
  while (i < lines.length) {
    const m = lines[i].match(EMITTED_BLOCK_HEADING);
    if (!m) {
      i += 1;
      continue;
    }
    const sourceFile = m[1];
    const blockLines = [lines[i]];
    let j = i + 1;
    for (; j < lines.length; j += 1) {
      const line = lines[j];
      // A new block heading, a section heading ('## ' but not '### '), or the
      // footer ends the current block. EMITTED_BLOCK_HEADING is checked first
      // so a rendered heading is never mistaken for a section heading.
      if (EMITTED_BLOCK_HEADING.test(line)) break;
      if (line.startsWith("## ")) break;
      if (line === "---") break;
      blockLines.push(line);
    }
    // The single '\n\n' join blank line trails every block; a parsed body is
    // trimmed, so a trailing empty line is always separator, never content.
    while (blockLines.length > 1 && blockLines[blockLines.length - 1] === "") {
      blockLines.pop();
    }
    const renderedText = blockLines.join("\n");
    const start = lineStart[i];
    spans.push({
      emittedIndex: spans.length,
      sourceFile,
      renderedText,
      renderedDigest: sha256(renderedText),
      start,
      end: start + renderedText.length,
    });
    i = j;
  }
  return spans;
}

// One block-drift entry (read-only report). kind ∈ unchanged|replace|insert|
// delete. emitted_index is the position in the EXPECTED sequence (null for a
// delete, which exists only in the actual artifact). digests are null on the
// side where the block is absent.
function blockChange(kind, { emittedIndex, sourceFile, sourceBlockIndex, actual, expected }) {
  return {
    kind,
    emitted_index: emittedIndex,
    source_file: sourceFile,
    source_block_index: sourceBlockIndex ?? null,
    actual_rendered_digest: actual ?? null,
    expected_rendered_digest: expected ?? null,
  };
}

/**
 * Per-block drift between an actual artifact's emitted spans and the expected
 * build's spans. When both sides have the same length and same source-file
 * sequence (the dominant STALE case: in-place edits / an emit_version bump),
 * the comparison is positional — clean unchanged/replace. Otherwise it falls
 * back to an LCS alignment over rendered digests, collapsing an in-place
 * delete+insert into a replace. `expectedManifest` (buildArtifact().blockManifest,
 * index-aligned with expectedSpans) supplies source_block_index. Pure.
 */
export function compareBlockDrift(actualSpans, expectedSpans, expectedManifest = null) {
  const srcIdx = (k) => expectedManifest?.[k]?.source_block_index ?? null;
  const sameStructure =
    actualSpans.length === expectedSpans.length &&
    actualSpans.every((s, k) => s.sourceFile === expectedSpans[k].sourceFile);

  if (sameStructure) {
    return expectedSpans.map((b, k) => {
      const a = actualSpans[k];
      const same = a.renderedDigest === b.renderedDigest;
      return blockChange(same ? "unchanged" : "replace", {
        emittedIndex: k,
        sourceFile: b.sourceFile,
        sourceBlockIndex: srcIdx(k),
        actual: a.renderedDigest,
        expected: b.renderedDigest,
      });
    });
  }

  // LCS over rendered digests (deterministic; ties resolve toward delete-first).
  const a = actualSpans;
  const b = expectedSpans;
  const n = a.length;
  const m = b.length;
  const dp = Array.from({ length: n + 1 }, () => new Array(m + 1).fill(0));
  for (let i = n - 1; i >= 0; i -= 1) {
    for (let j = m - 1; j >= 0; j -= 1) {
      dp[i][j] =
        a[i].renderedDigest === b[j].renderedDigest
          ? dp[i + 1][j + 1] + 1
          : Math.max(dp[i + 1][j], dp[i][j + 1]);
    }
  }
  const raw = [];
  let i = 0;
  let j = 0;
  while (i < n && j < m) {
    if (a[i].renderedDigest === b[j].renderedDigest) {
      raw.push(blockChange("unchanged", { emittedIndex: j, sourceFile: b[j].sourceFile, sourceBlockIndex: srcIdx(j), actual: a[i].renderedDigest, expected: b[j].renderedDigest }));
      i += 1;
      j += 1;
    } else if (dp[i + 1][j] >= dp[i][j + 1]) {
      raw.push(blockChange("delete", { emittedIndex: null, sourceFile: a[i].sourceFile, sourceBlockIndex: null, actual: a[i].renderedDigest, expected: null }));
      i += 1;
    } else {
      raw.push(blockChange("insert", { emittedIndex: j, sourceFile: b[j].sourceFile, sourceBlockIndex: srcIdx(j), actual: null, expected: b[j].renderedDigest }));
      j += 1;
    }
  }
  while (i < n) {
    raw.push(blockChange("delete", { emittedIndex: null, sourceFile: a[i].sourceFile, sourceBlockIndex: null, actual: a[i].renderedDigest, expected: null }));
    i += 1;
  }
  while (j < m) {
    raw.push(blockChange("insert", { emittedIndex: j, sourceFile: b[j].sourceFile, sourceBlockIndex: srcIdx(j), actual: null, expected: b[j].renderedDigest }));
    j += 1;
  }
  // Collapse an adjacent delete+insert (an in-place edit the LCS split) into a
  // single replace, preserving the expected emitted_index.
  const changes = [];
  for (let k = 0; k < raw.length; k += 1) {
    const cur = raw[k];
    const next = raw[k + 1];
    if (cur.kind === "delete" && next?.kind === "insert") {
      changes.push(blockChange("replace", {
        emittedIndex: next.emitted_index,
        sourceFile: next.source_file,
        sourceBlockIndex: next.source_block_index,
        actual: cur.actual_rendered_digest,
        expected: next.expected_rendered_digest,
      }));
      k += 1;
    } else {
      changes.push(cur);
    }
  }
  return changes;
}

/**
 * Read-only block-reconcile plan for one target, driven by an already-computed
 * classifyTarget `result` (single source of truth — never re-classifies). It
 * reports what a block-level reconcile WOULD do without writing:
 *   OK        -> reproducible, no drift (blocks empty).
 *   MISSING   -> reproducible create at the default profile (every expected
 *                block is an insert).
 *   STALE     -> if reproducible, the per-block drift against the recorded
 *                profile's expected build; if not, a refuse (no blocks).
 *   UNMANAGED / HAND-EDITED -> refuse (no blocks), mirroring file-level reconcile.
 * Pure aside from reading the on-disk artifact (never writes).
 */
export function planBlockReconcileTarget({ cwd, target, sources, result }) {
  const spec = EMIT_TARGETS[target];
  const path = spec.path;
  const base = { target, path, status: result.status };

  // Refuse classes: same boundary file-level reconcile enforces. No block patch.
  if (result.status === "unmanaged" || result.status === "hand-edited") {
    return { ...base, reproducible: false, expected_profile: null, would_write_paths: [], refuse_reason: reconcileRefusal(result), blocks: [] };
  }
  if (result.status === "stale" && !staleIsReproducible(result)) {
    return { ...base, reproducible: false, expected_profile: null, would_write_paths: [], refuse_reason: reconcileRefusal(result), blocks: [] };
  }

  if (result.status === "ok") {
    // Reproducible and already fresh: nothing to reconcile.
    return { ...base, reproducible: true, expected_profile: result.recordedProfile, would_write_paths: [], refuse_reason: null, blocks: [] };
  }

  if (result.status === "missing") {
    const expected = buildArtifact({ sources, target, profile: "default" });
    const expectedSpans = parseEmittedBlockSpans(expected.payload);
    const blocks = expectedSpans.map((b, k) =>
      blockChange("insert", { emittedIndex: k, sourceFile: b.sourceFile, sourceBlockIndex: expected.blockManifest[k]?.source_block_index, actual: null, expected: b.renderedDigest }),
    );
    return { ...base, reproducible: true, expected_profile: "default", would_write_paths: [path], refuse_reason: null, blocks };
  }

  // STALE + reproducible: diff the on-disk artifact against the recorded
  // target/profile's expected build (the same build a file-level reconcile uses).
  const expected = buildArtifact({ sources, target: result.recordedTarget, profile: result.recordedProfile });
  const actualContent = canonicalize(readFileSync(resolve(cwd, path), "utf8"));
  const actualParsed = parseEmitHeader(actualContent);
  const actualSpans = actualParsed ? parseEmittedBlockSpans(actualParsed.payload) : [];
  const expectedSpans = parseEmittedBlockSpans(expected.payload);
  const blocks = compareBlockDrift(actualSpans, expectedSpans, expected.blockManifest);
  return { ...base, reproducible: true, expected_profile: result.recordedProfile, would_write_paths: [path], refuse_reason: null, blocks };
}

/**
 * Patch-application primitive (Phase 3). Produce the reconciled artifact bytes
 * for one target from its current on-disk artifact, the EXPECTED full artifact
 * (the oracle a file-level reconcile would write), and the read-only `plan`.
 *
 * Safety is proven, not assumed: the surgical block splice is only a mechanism,
 * and the result is ALWAYS checked byte-for-byte against `expectedArtifact`
 * before it is returned. On any mismatch this returns { ok: false } with no
 * artifact, so a caller can never write unverified bytes. Returns
 * { ok, artifact, error }. Pure (string in / data out, no I/O, no writes).
 *
 * Surgical path: when the current artifact is managed and the drift is
 * replace-only (same block structure), only the changed block substrings and
 * the header are swapped in the current bytes — a minimal patch. Otherwise it
 * falls back to the expected bytes wholesale (structural change: insert/delete/
 * reorder/MISSING). Either way the byte guard is the final word.
 */
export function applyBlockReconcilePlan(currentArtifact, expectedArtifact, plan) {
  const exp = canonicalize(expectedArtifact);
  let patched = exp; // default: reproduce the oracle wholesale.

  const cur = canonicalize(currentArtifact);
  const curParsed = parseEmitHeader(cur);
  const expParsed = parseEmitHeader(exp);

  const replaceOnly =
    plan &&
    Array.isArray(plan.blocks) &&
    plan.blocks.length > 0 &&
    plan.blocks.every((b) => b.kind === "unchanged" || b.kind === "replace");

  if (curParsed && expParsed && replaceOnly) {
    const curSpans = parseEmittedBlockSpans(curParsed.payload);
    const expSpans = parseEmittedBlockSpans(expParsed.payload);
    if (curSpans.length === expSpans.length && curSpans.length === plan.blocks.length) {
      // Header text = everything up to and including the '-->' + '\n' separator.
      const expHeaderText = exp.slice(0, exp.length - expParsed.payload.length);
      let payload = curParsed.payload;
      // Splice changed blocks from last to first so earlier offsets stay valid.
      for (let k = curSpans.length - 1; k >= 0; k -= 1) {
        if (plan.blocks[k].kind === "replace") {
          payload =
            payload.slice(0, curSpans[k].start) +
            expSpans[k].renderedText +
            payload.slice(curSpans[k].end);
        }
      }
      patched = expHeaderText + payload;
    }
  }

  if (patched !== exp) {
    return {
      ok: false,
      artifact: null,
      error: "block-level reconcile patch did not reproduce the expected artifact bytes",
    };
  }
  return { ok: true, artifact: exp, error: null };
}

// ---------------------------------------------------------------------------
// CLI surface (W2 §7)
// ---------------------------------------------------------------------------

export function parseEmitArgv(argv = process.argv.slice(2)) {
  const parsed = {
    targets: [],
    targetFlagGiven: false,
    check: false,
    explain: false,
    reconcile: false,
    blockLevel: false,
    blockManifest: false,
    blockReconcilePlan: false,
    force: false,
    full: false,
    format: "text",
    cwd: process.cwd(),
    help: false,
  };

  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--target") {
      parsed.targetFlagGiven = true;
      const ids = String(argv[++i] ?? "")
        .split(",")
        .map((id) => id.trim())
        .filter(Boolean);
      parsed.targets.push(...ids);
    } else if (arg === "--check") {
      parsed.check = true;
    } else if (arg === "--explain") {
      parsed.explain = true;
    } else if (arg === "--reconcile") {
      parsed.reconcile = true;
    } else if (arg === "--block-level") {
      parsed.blockLevel = true;
    } else if (arg === "--block-manifest") {
      parsed.blockManifest = true;
    } else if (arg === "--block-reconcile-plan") {
      parsed.blockReconcilePlan = true;
    } else if (arg === "--force") {
      parsed.force = true;
    } else if (arg === "--full") {
      parsed.full = true;
    } else if (arg === "--format") {
      const f = argv[++i] ?? "";
      if (f !== "text" && f !== "json") {
        throw new Error(`--format must be "text" or "json", got: ${f}`);
      }
      parsed.format = f;
    } else if (arg === "--cwd") {
      parsed.cwd = resolve(argv[++i] ?? parsed.cwd);
    } else if (arg === "-h" || arg === "--help") {
      parsed.help = true;
    } else {
      throw new Error(`Unknown argument: ${arg}`);
    }
  }

  const allowed = V1_TARGET_IDS.map((t) => `"${t}"`).join(", ");
  for (const id of parsed.targets) {
    if (!EMIT_TARGETS[id]?.v1) {
      throw new Error(`--target must be one of ${allowed}, got: ${id}`);
    }
  }
  if (parsed.targetFlagGiven && parsed.targets.length === 0) {
    throw new Error(`--target must be one of ${allowed}, got: (empty)`);
  }
  if (parsed.full && parsed.check) {
    throw new Error(
      "--full cannot be combined with --check (--check verifies against the profile recorded in the artifact header)",
    );
  }
  if (parsed.force && parsed.check) {
    throw new Error("--force cannot be combined with --check (--check never writes)");
  }
  // --explain is a read-only annotation on the check verdict; it has no meaning
  // in write mode and must never write, so it is valid only alongside --check.
  if (parsed.explain && !parsed.check) {
    throw new Error("--explain is only valid together with --check (it never writes)");
  }
  // --reconcile is a write mode; --check is read-only. They are opposite modes,
  // so combining them is a usage error.
  if (parsed.reconcile && parsed.check) {
    throw new Error("--reconcile cannot be combined with --check (--check never writes; --reconcile is the write side)");
  }
  // --reconcile re-emits each STALE target against the profile recorded in its
  // header, so honoring --full would silently override that recorded profile
  // (e.g. degrade or upgrade a target). Refuse the combination outright.
  if (parsed.reconcile && parsed.full) {
    throw new Error("--full cannot be combined with --reconcile (--reconcile re-emits each target against the profile recorded in its header)");
  }
  // --block-level is a modifier on --reconcile: it makes reconcile repair drift
  // with a block-level patch (proven byte-identical to the file-level reconcile)
  // instead of a whole-file rewrite. It is meaningless without --reconcile.
  if (parsed.blockLevel && !parsed.reconcile) {
    throw new Error("--block-level is only valid together with --reconcile (it selects the block-level reconcile patch path)");
  }
  // --block-manifest is an opt-in, read-only annotation that attaches per-block
  // provenance to the structured check verdict. It is structured data with no
  // text rendering, and it never writes, so it is valid ONLY alongside
  // --check --explain --format json. Any other combination is a usage error.
  if (
    parsed.blockManifest &&
    !(parsed.check && parsed.explain && parsed.format === "json")
  ) {
    throw new Error(
      "--block-manifest is only valid with --check --explain --format json (it is read-only structured provenance and never writes)",
    );
  }
  // --block-reconcile-plan is the read-only preview of a block-level reconcile:
  // per-target drift (which emitted blocks would change) with no write. Same
  // opt-in surface as --block-manifest.
  if (
    parsed.blockReconcilePlan &&
    !(parsed.check && parsed.explain && parsed.format === "json")
  ) {
    throw new Error(
      "--block-reconcile-plan is only valid with --check --explain --format json (it is a read-only drift preview and never writes)",
    );
  }

  // Default target set: all v1 targets (W1 §2, W2 §8 ruling). Explicit
  // targets are deduped and processed in registry order regardless of flag
  // order (determinism, W2 §7.1).
  const requested = parsed.targetFlagGiven ? new Set(parsed.targets) : new Set(V1_TARGET_IDS);
  parsed.targets = V1_TARGET_IDS.filter((id) => requested.has(id));

  return parsed;
}

// W2 §8(b) dual-target advisory — a pure function of the flag set, printed
// only on a no---target emit of both v1 targets; never in artifact bytes.
export const DUAL_TARGET_NOTE = [
  "note: AGENTS.md and CLAUDE.md carry identical payloads. If every tool you run",
  "reads AGENTS.md, emit only it: mind-ontology emit --target agents-md",
].join("\n");

function budgetWarning(build) {
  const contributors = [...build.lineContributions.entries()]
    .filter(([, lines]) => lines > 0)
    .sort(
      (a, b) => b[1] - a[1] || SOURCE_FILES.indexOf(a[0]) - SOURCE_FILES.indexOf(b[0]),
    )
    .slice(0, 3)
    .map(([file, lines]) => `${file} (${lines} lines)`)
    .join(", ");
  return `warning: ${build.target} payload is ${build.payloadLines} lines (soft budget ${PAYLOAD_LINE_BUDGET}); largest contributors: ${contributors}`;
}

/**
 * Write mode (W2 §7.2). Returns { exitCode, stdout, stderr }.
 * Multi-target emits are all-or-nothing: an UNMANAGED refusal writes nothing
 * for any target. Rewriting a fresh artifact is a byte-identical no-op.
 */
export function runEmitWrite(options) {
  validateAgentctxSources(options.cwd);
  const sources = readAgentctx(options.cwd);
  const profile = options.full ? "full" : "default";

  const builds = options.targets.map((target) => buildArtifact({ sources, target, profile }));

  // Refusal scan before any write (W1 §9): an existing headerless file is
  // never silently overwritten and never merged; --force is the only override.
  if (!options.force) {
    for (const build of builds) {
      const path = resolve(options.cwd, build.path);
      if (
        existsSync(path) &&
        parseEmitHeader(canonicalize(readFileSync(path, "utf8"))) === null
      ) {
        throw new Error(
          `Refusing to overwrite ${build.path}: file exists but has no emit header. Move its content into .agentctx/ sources, then re-run with --force to overwrite.`,
        );
      }
    }
  }

  for (const build of builds) {
    const path = resolve(options.cwd, build.path);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, build.artifact, "utf8");
  }

  const warnings = [];
  for (const build of builds) {
    if (build.payloadLines > PAYLOAD_LINE_BUDGET) {
      warnings.push({
        type: "budget-overflow",
        target: build.target,
        payload_lines: build.payloadLines,
        budget: PAYLOAD_LINE_BUDGET,
        message: budgetWarning(build),
      });
    }
  }
  if (!options.targetFlagGiven) {
    warnings.push({ type: "dual-target-note", message: DUAL_TARGET_NOTE });
  }

  let stdout;
  if (options.format === "json") {
    stdout =
      JSON.stringify(
        {
          ok: true,
          written: builds.map((build) => ({
            target: build.target,
            path: build.path,
            profile: build.profile,
            emit_version: EMIT_VERSION,
            source_digest: build.sourceDigest,
            content_digest: build.contentDigest,
            payload_lines: build.payloadLines,
          })),
          warnings: warnings.map(({ message, ...rest }) => rest),
        },
        null,
        2,
      ) + "\n";
  } else {
    stdout =
      builds
        .map(
          (build) =>
            `WROTE  ${build.path}  (${build.target}, profile ${build.profile}, ${build.payloadLines} payload lines)`,
        )
        .join("\n") + "\n";
  }

  const stderr = warnings.map((w) => w.message).join("\n");
  return { exitCode: 0, stdout, stderr: stderr ? `${stderr}\n` : "" };
}

const TEXT_STATUS = {
  ok: "OK",
  missing: "MISSING",
  unmanaged: "UNMANAGED",
  "hand-edited": "HAND-EDITED",
  stale: "STALE",
};

/**
 * The check verdict as data (W2 §7.4 shape) — one shape, two consumers:
 * `emit --check --format json` prints it verbatim, and the W7 `status`
 * command embeds it verbatim as its emit section.
 *
 * `explainByTarget` (a Map target -> explain object) is opt-in: when omitted
 * the shape is byte-for-byte the frozen base shape (mandatory back-compat, and
 * what `status` always embeds). When present, each target gains an `explain`
 * key. It is never set on the `status` path.
 *
 * `manifestByTarget` (a Map target -> block-manifest array | null) is a further
 * opt-in: when present each target gains a `block_manifest` key carrying the
 * per-block provenance (Phase 2), or null when the recorded profile is not
 * reproducible. Only ever set under --check --explain --format json
 * --block-manifest; never on the `status` path.
 *
 * `planByTarget` (a Map target -> block-reconcile-plan object) is a further
 * opt-in: when present each target gains a `block_reconcile_plan` key (lane 4)
 * previewing the per-block drift a block-level reconcile would repair. Only ever
 * set under --check --explain --format json --block-reconcile-plan; never on the
 * `status` path.
 */
export function checkResultJson(
  results,
  explainByTarget = null,
  manifestByTarget = null,
  planByTarget = null,
) {
  return {
    ok: results.every((r) => r.status === "ok"),
    targets: results.map((r) => {
      const base = {
        target: r.target,
        path: r.path,
        status: r.status,
        detail: r.detail,
      };
      if (explainByTarget) base.explain = explainByTarget.get(r.target);
      if (manifestByTarget) base.block_manifest = manifestByTarget.get(r.target);
      if (planByTarget) base.block_reconcile_plan = planByTarget.get(r.target);
      return base;
    }),
  };
}

/**
 * The check verdict as text: one line per target plus the frozen summary
 * line ("OK - n of n targets fresh" / "DRIFT - n of m targets need
 * attention"). Shared with `status` so both screens render freshness
 * identically.
 */
export function renderCheckText(results, explainByTarget = null) {
  const drifted = results.filter((r) => r.status !== "ok");
  const lines = [];
  for (const r of results) {
    lines.push(
      r.status === "ok"
        ? `${TEXT_STATUS.ok.padEnd(13)}${r.path} (${r.target}, profile ${r.profile})`
        : `${TEXT_STATUS[r.status].padEnd(13)}${r.path} (${r.target}) - ${r.detail}`,
    );
    // --explain only: an indented explanation line after each classification.
    // Absent explainByTarget (the default and the `status` embed) leaves the
    // existing output byte-for-byte unchanged.
    if (explainByTarget) {
      lines.push(`             ${explainText(r, explainByTarget.get(r.target))}`);
    }
  }
  lines.push(
    drifted.length === 0
      ? `OK - ${results.length} of ${results.length} targets fresh`
      : `DRIFT - ${drifted.length} of ${results.length} targets need attention`,
  );
  return lines.join("\n") + "\n";
}

/**
 * Classify every requested target from in-memory sources (the `--check`
 * core, also embedded by `status`).
 */
export function checkTargets({ cwd, targets, sources }) {
  return targets.map((target) => classifyTarget({ cwd, target, sources }));
}

/**
 * Check mode (W1 §8, W2 §7.3-7.4). Writes nothing. A negative verdict is a
 * successful report of a bad state: report on stdout, exit 1. Hard errors
 * (compile failure, usage errors) are thrown and exit 2 in the entry point.
 */
export function runEmitCheck(options) {
  validateAgentctxSources(options.cwd);
  const sources = readAgentctx(options.cwd);

  const results = checkTargets({ cwd: options.cwd, targets: options.targets, sources });
  const ok = results.every((r) => r.status === "ok");

  // --explain (read-only): derive the per-target explanation from the same
  // sources and the already-computed classification. Off by default, so the
  // base text/json output stays byte-for-byte unchanged.
  const explainByTarget = options.explain
    ? new Map(
        results.map((r) => [
          r.target,
          explainTarget({ cwd: options.cwd, target: r.target, sources, result: r }),
        ]),
      )
    : null;

  // --block-manifest (read-only, opt-in; requires --explain --format json):
  // attach the per-block provenance the current sources produce for each target
  // under the profile --explain already reports (recorded profile if managed,
  // else default). It is null whenever the recorded header is NOT reproducible
  // — an unknown recorded profile OR a non-v1 recorded target — so it stays in
  // lock-step with --explain's own reproducibility signal
  // (sourceDigestMatchesCurrent === null while a header is present) and never
  // claims provenance for an artifact it cannot rebuild. Reuses buildArtifact;
  // no writes.
  const manifestByTarget = options.blockManifest
    ? new Map(
        results.map((r) => {
          const explain = explainByTarget.get(r.target);
          // A header is present but its recorded target/profile cannot be
          // reproduced (the same gate classify/reconcile/explain apply): the
          // on-disk artifact's provenance is unrecomputable -> null.
          if (explain.headerPresent && explain.sourceDigestMatchesCurrent === null) {
            return [r.target, null];
          }
          // Otherwise expectedProfile is reproducible: the recorded profile for
          // a managed target, or the default for a fresh (MISSING/UNMANAGED)
          // emit. PROFILES guard is defensive — this branch only sees known
          // profiles.
          const manifest = PROFILES[explain.expectedProfile]
            ? buildArtifact({ sources, target: r.target, profile: explain.expectedProfile }).blockManifest
            : null;
          return [r.target, manifest];
        }),
      )
    : null;

  // --block-reconcile-plan (read-only, opt-in; requires --explain --format json):
  // preview the per-block drift a block-level reconcile would repair. Derived
  // from planBlockReconcileTarget on the same classification; no writes. The
  // target/path are already on the parent entry, so embed only the plan body.
  const planByTarget = options.blockReconcilePlan
    ? new Map(
        results.map((r) => {
          const { reproducible, expected_profile, would_write_paths, refuse_reason, blocks } =
            planBlockReconcileTarget({ cwd: options.cwd, target: r.target, sources, result: r });
          return [r.target, { reproducible, expected_profile, would_write_paths, refuse_reason, blocks }];
        }),
      )
    : null;

  const stdout =
    options.format === "json"
      ? JSON.stringify(checkResultJson(results, explainByTarget, manifestByTarget, planByTarget), null, 2) + "\n"
      : renderCheckText(results, explainByTarget);

  return { exitCode: ok ? 0 : 1, stdout, stderr: "" };
}

// A reconcile refuses any class where a re-emit could destroy unrecoverable
// work or cannot be reproduced safely. The message names the manual fix.
function reconcileRefusal(result) {
  switch (result.status) {
    case "unmanaged":
      return `${result.path} (${result.target}) is UNMANAGED (a headerless file emit will not claim); reconcile will not overwrite it. Move its content into .agentctx/ sources, then run: mind-ontology emit --force --target ${result.target}`;
    case "hand-edited":
      return `${result.path} (${result.target}) is HAND-EDITED; a re-emit would discard the hand edit. Move the edit into the .agentctx/ source, then run: mind-ontology emit --target ${result.target}`;
    default:
      // A STALE target whose recorded target/profile is no longer reproducible
      // (unknown profile / non-v1 target in the header): re-emitting would have
      // to invent a profile, which could silently change the artifact's scope.
      return `${result.path} (${result.target}) records a target/profile that is no longer reproducible; reconcile will not guess a profile. Re-emit it explicitly with a known profile.`;
  }
}

// Whether a STALE artifact can be reconciled by rebuilding against the
// target/profile RECORDED IN ITS HEADER. emit_version-only staleness is
// reproducible (the recorded names are still known); a header recording an
// unknown profile or a non-v1 target is NOT — judged from the recorded fields,
// never the requested target (the same test classifyTarget itself applies, and
// what --check --explain reports). A missing/headerless result has no recorded
// fields and is handled by other branches, never reaches here.
function staleIsReproducible(result) {
  return Boolean(
    EMIT_TARGETS[result.recordedTarget]?.v1 && PROFILES[result.recordedProfile],
  );
}

/**
 * Reconcile mode (Lane 2). SAFE drift repair: writes generated artifacts
 * (AGENTS.md / CLAUDE.md) only — never `.agentctx/` sources — and only for
 * classes where nothing is lost:
 *   OK          -> skip (already fresh).
 *   MISSING     -> emit at the default profile (nothing on disk to honor).
 *   STALE       -> re-emit against the profile RECORDED IN THE HEADER, so a
 *                  `full` artifact stays `full` (never degraded to default).
 *   UNMANAGED   -> refuse (headerless file; needs --force).
 *   HAND-EDITED -> refuse (a re-emit would discard the hand edit).
 * All-or-nothing: if ANY requested target is in a refuse class, nothing is
 * written for any target. Classification happens first, every write second.
 * Returns { exitCode, stdout, stderr }: 0 reconciled/clean, 1 refused.
 */
export function runEmitReconcile(options) {
  validateAgentctxSources(options.cwd);
  const sources = readAgentctx(options.cwd);

  const results = checkTargets({ cwd: options.cwd, targets: options.targets, sources });

  // Phase 1 — classify and screen. A refuse class anywhere blocks the whole
  // run; collect every reason so the operator sees all of them at once.
  const refusals = results
    .filter(
      (r) =>
        r.status === "unmanaged" ||
        r.status === "hand-edited" ||
        (r.status === "stale" && !staleIsReproducible(r)),
    )
    .map((r) => reconcileRefusal(r));
  if (refusals.length > 0) {
    return {
      exitCode: 1,
      stdout: "",
      stderr:
        `Refusing to reconcile: ${refusals.length} target(s) need a human (nothing written for any target).\n` +
        refusals.map((m) => `  ${m}`).join("\n") +
        "\n",
    };
  }

  // Phase 2 — build every artifact in memory. STALE rebuilds against the
  // target/profile RECORDED IN THE HEADER (the same fields the reproducibility
  // gate and classifyTarget use), so a `full` artifact stays `full`. MISSING
  // has no header, so it emits the requested target at the default profile.
  // No write has happened yet.
  const planned = [];
  for (const r of results) {
    if (r.status === "ok") continue;
    const build =
      r.status === "stale"
        ? buildArtifact({ sources, target: r.recordedTarget, profile: r.recordedProfile })
        : buildArtifact({ sources, target: r.target, profile: "default" });
    planned.push({ result: r, build });
  }

  // Phase 3 — write all planned artifacts. Reconcile only ever writes the v1
  // artifact paths (AGENTS.md / CLAUDE.md), never `.agentctx/`.
  for (const { build } of planned) {
    const path = resolve(options.cwd, build.path);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, build.artifact, "utf8");
  }

  const reconciled = new Set(planned.map((p) => p.result.target));
  if (options.format === "json") {
    const stdout =
      JSON.stringify(
        {
          ok: true,
          targets: results.map((r) => ({
            target: r.target,
            path: r.path,
            action: reconciled.has(r.target) ? "reconciled" : "skipped",
            status: r.status,
            profile: reconciled.has(r.target)
              ? planned.find((p) => p.result.target === r.target).build.profile
              : (r.profile ?? null),
          })),
        },
        null,
        2,
      ) + "\n";
    return { exitCode: 0, stdout, stderr: "" };
  }

  const lines = results.map((r) => {
    if (!reconciled.has(r.target)) {
      return `SKIP        ${r.path} (${r.target}, already ${TEXT_STATUS[r.status]})`;
    }
    const build = planned.find((p) => p.result.target === r.target).build;
    return `RECONCILED  ${r.path} (${r.target}, was ${TEXT_STATUS[r.status]}, profile ${build.profile})`;
  });
  lines.push(
    reconciled.size === 0
      ? `OK - ${results.length} of ${results.length} targets already fresh`
      : `RECONCILED - ${reconciled.size} of ${results.length} targets re-emitted`,
  );
  return { exitCode: 0, stdout: lines.join("\n") + "\n", stderr: "" };
}

/**
 * Block-level reconcile mode (lane 4, Phase 4; opt-in `--reconcile --block-level`).
 * SAME safety contract and refusal rules as the file-level reconcile above —
 * OK skip, MISSING/STALE repair, UNMANAGED/HAND-EDITED/unreproducible-STALE
 * refuse, all-or-nothing, never `.agentctx/`. The ONLY difference is the repair
 * mechanism: each drifted target is patched at block granularity and the result
 * is proven byte-for-byte identical to what the file-level reconcile would write
 * (applyBlockReconcilePlan's guard) BEFORE any file is touched. A guard failure
 * anywhere refuses the whole run, so a block-patch bug can never emit corrupted
 * bytes. Classification + every byte guard complete first; writes happen last.
 */
export function runEmitReconcileBlockLevel(options) {
  validateAgentctxSources(options.cwd);
  const sources = readAgentctx(options.cwd);

  const results = checkTargets({ cwd: options.cwd, targets: options.targets, sources });

  // Phase 1 — same refusal screen as file-level reconcile (single source of truth).
  const refusals = results
    .filter(
      (r) =>
        r.status === "unmanaged" ||
        r.status === "hand-edited" ||
        (r.status === "stale" && !staleIsReproducible(r)),
    )
    .map((r) => reconcileRefusal(r));
  if (refusals.length > 0) {
    return {
      exitCode: 1,
      stdout: "",
      stderr:
        `Refusing to reconcile: ${refusals.length} target(s) need a human (nothing written for any target).\n` +
        refusals.map((m) => `  ${m}`).join("\n") +
        "\n",
    };
  }

  // Phase 2 — build the expected artifact, the read-only plan, and the patched
  // bytes for every drifted target IN MEMORY. The same expected build the
  // file-level reconcile uses is the oracle; applyBlockReconcilePlan proves the
  // block patch reproduces it. A guard failure refuses the whole run.
  const planned = [];
  for (const r of results) {
    if (r.status === "ok") continue;
    const build =
      r.status === "stale"
        ? buildArtifact({ sources, target: r.recordedTarget, profile: r.recordedProfile })
        : buildArtifact({ sources, target: r.target, profile: "default" });
    const plan = planBlockReconcileTarget({ cwd: options.cwd, target: r.target, sources, result: r });
    const artifactPath = resolve(options.cwd, build.path);
    const current = existsSync(artifactPath) ? readFileSync(artifactPath, "utf8") : "";
    const applied = applyBlockReconcilePlan(current, build.artifact, plan);
    if (!applied.ok) {
      return {
        exitCode: 1,
        stdout: "",
        stderr:
          `Refusing to reconcile: the block-level patch for ${build.path} (${r.target}) failed its byte-equality guard (nothing written for any target).\n  ${applied.error}\n`,
      };
    }
    const changedBlocks = plan.blocks.filter((b) => b.kind !== "unchanged").length;
    planned.push({ result: r, build, artifact: applied.artifact, changedBlocks });
  }

  // Phase 3 — write all patched artifacts. Each is byte-identical to a
  // file-level reconcile; only v1 artifact paths are written, never `.agentctx/`.
  for (const { build, artifact } of planned) {
    const path = resolve(options.cwd, build.path);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, artifact, "utf8");
  }

  const byTarget = new Map(planned.map((p) => [p.result.target, p]));
  if (options.format === "json") {
    const stdout =
      JSON.stringify(
        {
          ok: true,
          mode: "block-level",
          targets: results.map((r) => {
            const p = byTarget.get(r.target);
            return {
              target: r.target,
              path: r.path,
              action: p ? "block-reconciled" : "skipped",
              status: r.status,
              profile: p ? p.build.profile : (r.profile ?? null),
              changed_blocks: p ? p.changedBlocks : 0,
            };
          }),
        },
        null,
        2,
      ) + "\n";
    return { exitCode: 0, stdout, stderr: "" };
  }

  const lines = results.map((r) => {
    const p = byTarget.get(r.target);
    if (!p) {
      return `SKIP            ${r.path} (${r.target}, already ${TEXT_STATUS[r.status]})`;
    }
    return `BLOCK-RECONCILED ${r.path} (${r.target}, was ${TEXT_STATUS[r.status]}, profile ${p.build.profile}, ${p.changedBlocks} block(s))`;
  });
  lines.push(
    byTarget.size === 0
      ? `OK - ${results.length} of ${results.length} targets already fresh`
      : `BLOCK-RECONCILED - ${byTarget.size} of ${results.length} targets repaired at block level`,
  );
  return { exitCode: 0, stdout: lines.join("\n") + "\n", stderr: "" };
}

function printHelp() {
  return `mind-ontology emit — compile static per-tool artifacts from .agentctx/

Usage:
  mind-ontology emit [options]             write all v1 targets (AGENTS.md, CLAUDE.md)
  mind-ontology emit --check [options]     verify freshness; writes nothing
  mind-ontology emit --reconcile [options] safely re-emit only drifted targets

Options:
  --target <id>[,<id>]   Restrict to targets: agents-md, claude-md. Repeatable.
  --check                Classify each target (OK/MISSING/UNMANAGED/HAND-EDITED/STALE).
                         Exit 0 fresh, 1 drift, 2 error.
  --explain              With --check only: explain why each target got its class
                         and what a reconcile would write. Read-only; never writes.
  --block-manifest       With --check --explain --format json only: attach
                         per-block provenance (source_file/source_block_index/
                         source_block_digest/rendered_digest/...) to each target.
                         Read-only; never writes.
  --block-reconcile-plan With --check --explain --format json only: preview the
                         per-block drift a block-level reconcile would repair
                         (unchanged/replace/insert/delete). Read-only; never writes.
  --reconcile            Repair drift safely: re-emit MISSING/STALE targets
                         (STALE keeps its recorded profile), SKIP OK ones, and
                         REFUSE UNMANAGED/HAND-EDITED (writing nothing for any
                         target). Writes artifacts only, never .agentctx/.
                         Exit 0 reconciled/clean, 1 refused, 2 error.
  --block-level          With --reconcile only: repair drift with a block-level
                         patch instead of a whole-file rewrite. Proven
                         byte-identical to the file-level reconcile (a failed
                         byte guard refuses the whole run). Same refusal rules.
  --force                Overwrite an existing un-managed file (one without an emit
                         header). Never needed for refreshing managed artifacts.
  --full                 Emit the whole ontology instead of the default profile.
  --format text|json     Output format (default: text).
  --cwd <path>           Project root containing .agentctx/ (default: cwd).
  -h, --help             Show this help message.

Both files carry identical payloads by design; if every tool you run reads
AGENTS.md, emit only it: mind-ontology emit --target agents-md
`;
}

const isMain = process.argv[1] === fileURLToPath(import.meta.url);

if (isMain) {
  // Exit-code contract (W2 §2.4): write mode is 0/1; check mode is the
  // three-way split — 0 fresh, 1 drift, 2 hard error (usage errors and
  // compile failures included, so `1` means exactly "re-emit needed").
  const argv = process.argv.slice(2);
  // Exit code on a thrown usage/parse error. --check and --explain imply
  // check-mode intent; --reconcile is a distinct mode that also reserves exit 2
  // for usage errors (1 stays reserved for a reconcile refusal — a real verdict,
  // not a usage mistake). Plain write-mode usage errors stay exit 1.
  const usageExit2 =
    argv.includes("--check") ||
    argv.includes("--explain") ||
    argv.includes("--reconcile") ||
    argv.includes("--block-level") ||
    argv.includes("--block-manifest") ||
    argv.includes("--block-reconcile-plan");
  try {
    const options = parseEmitArgv(argv);
    if (options.help) {
      process.stdout.write(printHelp());
      process.exit(0);
    }
    const result = options.check
      ? runEmitCheck(options)
      : options.reconcile
        ? options.blockLevel
          ? runEmitReconcileBlockLevel(options)
          : runEmitReconcile(options)
        : runEmitWrite(options);
    if (result.stdout) process.stdout.write(result.stdout);
    if (result.stderr) process.stderr.write(result.stderr);
    process.exit(result.exitCode);
  } catch (error) {
    process.stderr.write(`${error.message}\n`);
    process.exit(usageExit2 ? 2 : 1);
  }
}
