#!/usr/bin/env node

/**
 * mind-ontology emit — compile static per-tool artifacts from .agentctx/.
 *
 * Implements ADL W3 of the Workbench v1 design packet against the normative
 * specs:
 *   - docs/workbench-w1-emit-target-spec.md (targets, profiles, header,
 *     determinism, drift classes)
 *   - docs/workbench-w2-cli-spec.md (flags, streams, exit codes, JSON shapes)
 *
 * Determinism invariant (W1 §7): emitted bytes are a pure function of
 * (canonicalized included source bytes, target id, profile, emit_version).
 * No timestamps, no machine identity, no locale-dependent ordering, no
 * randomness, no network or model calls anywhere in this module.
 */

import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  SAFETY_TAGS,
  SOURCE_FILES,
  parseMarkdownBlocks,
  readAgentctx,
  validateAgentctxSources,
} from "./compile.mjs";

// 2: cq.md exempted from the safety sweep (W4 operator ruling, W1 §3) —
// payloads emitted under version 1 no longer match and re-flag as STALE.
export const EMIT_VERSION = 2;

// W4 operator ruling (W1 §3): competency questions are questions, not
// executable constraints — a #safety tag on a CQ marks its topic (the CQ
// schema's required safety question), not an enforceable rule. Sweeping an
// unanswered question into the Constraints section would put a
// non-instruction into an instruction file, so cq.md never participates in
// the safety sweep. The live MCP path owns CQ surfacing.
export const SWEEP_EXEMPT_FILES = new Set(["cq.md"]);

// Normative target registry (W1 §2). Ids are stable forever; the registry-sync
// guard test asserts this constant matches the W1 spec table. Only `v1: true`
// targets are emittable today; the fast-follow rows are registered so their
// ids and artifact paths stay reserved.
export const EMIT_TARGETS = {
  "agents-md": { path: "AGENTS.md", title: "# AGENTS.md", v1: true },
  "claude-md": { path: "CLAUDE.md", title: "# CLAUDE.md", v1: true },
  cursor: { path: ".cursor/rules/mind-ontology.mdc", title: null, v1: false },
  "paste-block": { path: "mind-ontology-paste-block.md", title: null, v1: false },
};

export const V1_TARGET_IDS = Object.keys(EMIT_TARGETS).filter(
  (id) => EMIT_TARGETS[id].v1,
);

// Profiles are fixed engine constants (W1 §3; W2 §12: no profile editing) so
// --check can always recompile from the header's recorded profile name.
export const PROFILES = {
  default: {
    "constraints.md": "all",
    "identity.md": "all",
    "direction.md": "all",
    "projects.md": "none",
    "decisions.md": "none",
    "architecture.md": "none",
    "agent-roles.md": "all",
    "glossary.md": "none",
    "cq.md": "none",
  },
  full: Object.fromEntries(SOURCE_FILES.map((file) => [file, "all"])),
};

// Generated `##` section per source file. Section order is always
// SOURCE_FILES order (W1 §3); under the default profile that yields exactly
// the Constraints -> Identity -> Direction -> Agent roles order W1 §4 lists.
export const SECTION_TITLES = {
  "constraints.md": "Constraints",
  "identity.md": "Identity",
  "direction.md": "Direction",
  "projects.md": "Projects",
  "decisions.md": "Decisions",
  "architecture.md": "Architecture",
  "agent-roles.md": "Agent roles",
  "glossary.md": "Glossary",
  "cq.md": "Competency questions",
};

export const PAYLOAD_LINE_BUDGET = 400;

export const REQUIRED_HEADER_KEYS = [
  "target",
  "profile",
  "emit_version",
  "source",
  "source_digest",
  "content_digest",
  "note",
];

const HEADER_OPEN = "<!-- mind-ontology:emit";
const HEADER_CLOSE = "-->";
// ASCII only (W1 §6) so the header survives naive encoding round-trips.
const HEADER_NOTE =
  "GENERATED FILE - do not hand-edit. Edit .agentctx/ and re-run: mind-ontology emit";

// Per-target frame text (W1 §4-5). The payload blocks are byte-identical
// across targets (W1 principle 3); only these frame pieces differ. The
// CLAUDE.md notice carries the ratified W2 §8(c) amendment, shipped in the
// first golden so it never costs an emit_version bump.
const FRAMES = {
  "agents-md": {
    notice: [
      "> Generated by `mind-ontology emit` from `.agentctx/` — **do not hand-edit.**",
      "> Edit the source files and re-run `mind-ontology emit`. Agents with MCP",
      "> access get richer, task-scoped context from the live `get_context` tool.",
    ],
    footer: [
      "---",
      "*Source: `.agentctx/` · refresh: `mind-ontology emit` · verify: `mind-ontology emit --check`*",
    ],
  },
  "claude-md": {
    notice: [
      "> Generated by `mind-ontology emit` from `.agentctx/` — **do not hand-edit.**",
      "> Claude Code reads this file as project memory. Edit the source files and",
      "> re-run `mind-ontology emit`. Agents get richer, task-scoped context from",
      "> the live `agentctx` MCP server (`get_context` / `list_constraints`).",
      "> If your tooling also loads `AGENTS.md`, the two files carry identical",
      "> payloads — keep whichever your tools read and re-emit only that target.",
    ],
    footer: [
      "---",
      "*Source: `.agentctx/` · refresh: `mind-ontology emit` · verify: `mind-ontology emit --check`*",
      "*Per-user overrides belong in `CLAUDE.local.md` or user memory, not in this generated file.*",
    ],
  },
};

// W1 §7 canonicalization: strip a leading UTF-8 BOM, normalize CRLF -> LF,
// nothing else. Applied everywhere bytes are parsed, hashed, or compared.
export function canonicalize(text) {
  return String(text).replace(/^\uFEFF/, "").replace(/\r\n/g, "\n");
}

export function sha256(text) {
  return `sha256:${createHash("sha256").update(text, "utf8").digest("hex")}`;
}

function isSafetyBlock(block) {
  return block.tags.some((tag) => SAFETY_TAGS.has(tag));
}

function renderBlock(block) {
  // W1 §4 block rendering, identical across targets: heading title with tags
  // stripped, HTML provenance comment naming the true source file, body
  // verbatim. Source-level ## blocks render as ### so they nest under the
  // generated ## sections.
  const heading = `### ${block.title} <!-- (from .agentctx/${block.file}) -->`;
  return block.body ? `${heading}\n${block.body}` : heading;
}

/**
 * Build one target artifact entirely in memory.
 * Returns { target, path, profile, payload, artifact, sourceDigest,
 *           contentDigest, payloadLines, lineContributions }.
 */
export function buildArtifact({ sources, target, profile = "default" }) {
  const spec = EMIT_TARGETS[target];
  if (!spec || !spec.v1) {
    throw new Error(
      `--target must be one of ${V1_TARGET_IDS.map((id) => `"${id}"`).join(", ")}, got: ${target}`,
    );
  }
  const rules = PROFILES[profile];
  if (!rules) {
    throw new Error(`Unknown emit profile: ${profile}`);
  }

  const canonical = {};
  const blocksByFile = {};
  for (const file of SOURCE_FILES) {
    canonical[file] = canonicalize(sources[file] ?? "");
    blocksByFile[file] = parseMarkdownBlocks(canonical[file], file);
  }

  // Safety sweep (W1 principle 4): safety-tagged blocks in excluded files are
  // forced into the Constraints section. A block selected by its own file's
  // rule is never re-appended. cq.md is exempt (SWEEP_EXEMPT_FILES).
  const forcedBlocks = [];
  const forcedFiles = new Set();
  for (const file of SOURCE_FILES) {
    if (rules[file] !== "none" || SWEEP_EXEMPT_FILES.has(file)) continue;
    for (const block of blocksByFile[file]) {
      if (isSafetyBlock(block)) {
        forcedBlocks.push(block);
        forcedFiles.add(file);
      }
    }
  }

  // Sections in SOURCE_FILES order; a section with zero blocks is omitted
  // entirely, heading included (W1 §4 empty-section rule).
  const sections = [];
  const lineContributions = new Map();
  const countLines = (file, text) => {
    lineContributions.set(
      file,
      (lineContributions.get(file) ?? 0) + text.split("\n").length,
    );
  };
  for (const file of SOURCE_FILES) {
    if (rules[file] === "none") continue;
    const blocks = [...blocksByFile[file]];
    if (file === "constraints.md") blocks.push(...forcedBlocks);
    if (blocks.length === 0) continue;
    const rendered = blocks.map((block) => {
      const text = renderBlock(block);
      countLines(block.file, text);
      return text;
    });
    sections.push(`## ${SECTION_TITLES[file]}\n\n${rendered.join("\n\n")}`);
  }

  const frame = FRAMES[target];
  const payload =
    [spec.title, frame.notice.join("\n"), ...sections, frame.footer.join("\n")].join(
      "\n\n",
    ) + "\n";

  // source_digest (W1 §6): fingerprint of the inputs over every
  // profile-included file, in SOURCE_FILES order, plus the one asymmetry:
  // excluded files that currently contribute >=1 safety-forced block are
  // digested too, so edits to them re-flag the artifact.
  const digestParts = [];
  for (const file of SOURCE_FILES) {
    if (rules[file] === "none" && !forcedFiles.has(file)) continue;
    digestParts.push(`${file}\n${canonical[file]}\0`);
  }
  const sourceDigest = sha256(digestParts.join(""));
  const contentDigest = sha256(payload);

  const header = [
    HEADER_OPEN,
    `target: ${target}`,
    `profile: ${profile}`,
    `emit_version: ${EMIT_VERSION}`,
    "source: .agentctx/",
    `source_digest: ${sourceDigest}`,
    `content_digest: ${contentDigest}`,
    `note: ${HEADER_NOTE}`,
    HEADER_CLOSE,
  ].join("\n");

  const payloadLines = payload.split("\n").length - 1; // newline-terminated lines

  return {
    target,
    path: spec.path,
    profile,
    payload,
    artifact: `${header}\n${payload}`,
    sourceDigest,
    contentDigest,
    payloadLines,
    lineContributions,
  };
}

/**
 * Parse a generated-file header (W1 §6) from canonicalized artifact content.
 * Returns { header, payload } or null when the content is not a managed
 * artifact (no header block, unparseable line, or missing a required key).
 * Unknown keys are ignored (forward compatibility).
 */
export function parseEmitHeader(content) {
  const lines = String(content).split("\n");
  if (lines[0] !== HEADER_OPEN) return null;
  const header = {};
  let closeIndex = -1;
  for (let i = 1; i < lines.length; i += 1) {
    if (lines[i] === HEADER_CLOSE) {
      closeIndex = i;
      break;
    }
    const m = lines[i].match(/^([A-Za-z0-9_-]+): (.*)$/);
    if (!m) return null;
    header[m[1]] = m[2];
  }
  if (closeIndex === -1) return null;
  for (const key of REQUIRED_HEADER_KEYS) {
    if (!(key in header)) return null;
  }
  return { header, payload: lines.slice(closeIndex + 1).join("\n") };
}

// Operator-guidance detail sentences (W1 §8 per-class table; wording locked
// here, mirrored in docs/cli-errors.md, and asserted by the check matrix
// guard test).
export function detailFor(status, target, path) {
  switch (status) {
    case "missing":
      return `artifact has never been emitted (or was deleted); run: mind-ontology emit --target ${target}`;
    case "unmanaged":
      return `file exists but is not managed by emit; emit will not touch it without --force. Move hand-written content into .agentctx/ sources, then run: mind-ontology emit --force --target ${target}`;
    case "hand-edited":
      return `file was edited after generation; hand edits will be lost on re-emit. Port the edits into .agentctx/ sources, then re-emit. Diff hint: git diff ${path}`;
    case "stale":
      return `.agentctx/ changed (or emit_version bumped) since last emit; run: mind-ontology emit --target ${target}`;
    default:
      return null;
  }
}

/**
 * Classify one target (W1 §8): mutually exclusive classes, checked in order
 * MISSING -> UNMANAGED -> HAND-EDITED -> STALE -> OK. The hand-edit check
 * runs before staleness so the artifact disagreeing with itself is reported
 * independently of whether sources also moved.
 */
export function classifyTarget({ cwd, target, sources }) {
  const spec = EMIT_TARGETS[target];
  const path = resolve(cwd, spec.path);

  if (!existsSync(path)) {
    return {
      target,
      path: spec.path,
      status: "missing",
      detail: detailFor("missing", target, spec.path),
    };
  }

  const content = canonicalize(readFileSync(path, "utf8"));
  const parsed = parseEmitHeader(content);
  if (!parsed) {
    return {
      target,
      path: spec.path,
      status: "unmanaged",
      detail: detailFor("unmanaged", target, spec.path),
    };
  }

  if (sha256(parsed.payload) !== parsed.header.content_digest) {
    return {
      target,
      path: spec.path,
      status: "hand-edited",
      detail: detailFor("hand-edited", target, spec.path),
      profile: parsed.header.profile,
    };
  }

  const stale = {
    target,
    path: spec.path,
    status: "stale",
    detail: detailFor("stale", target, spec.path),
    profile: parsed.header.profile,
  };
  if (parsed.header.emit_version !== String(EMIT_VERSION)) return stale;
  // A header naming an unknown target or profile cannot be reproduced by the
  // current generator; re-emitting (which records current names) resolves it.
  if (!EMIT_TARGETS[parsed.header.target]?.v1 || !PROFILES[parsed.header.profile]) {
    return stale;
  }

  const expected = buildArtifact({
    sources,
    target: parsed.header.target,
    profile: parsed.header.profile,
  });
  if (expected.artifact !== content) return stale;

  return { target, path: spec.path, status: "ok", detail: null, profile: parsed.header.profile };
}

// ---------------------------------------------------------------------------
// CLI surface (W2 §7)
// ---------------------------------------------------------------------------

export function parseEmitArgv(argv = process.argv.slice(2)) {
  const parsed = {
    targets: [],
    targetFlagGiven: false,
    check: false,
    force: false,
    full: false,
    format: "text",
    cwd: process.cwd(),
    help: false,
  };

  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--target") {
      parsed.targetFlagGiven = true;
      const ids = String(argv[++i] ?? "")
        .split(",")
        .map((id) => id.trim())
        .filter(Boolean);
      parsed.targets.push(...ids);
    } else if (arg === "--check") {
      parsed.check = true;
    } else if (arg === "--force") {
      parsed.force = true;
    } else if (arg === "--full") {
      parsed.full = true;
    } else if (arg === "--format") {
      const f = argv[++i] ?? "";
      if (f !== "text" && f !== "json") {
        throw new Error(`--format must be "text" or "json", got: ${f}`);
      }
      parsed.format = f;
    } else if (arg === "--cwd") {
      parsed.cwd = resolve(argv[++i] ?? parsed.cwd);
    } else if (arg === "-h" || arg === "--help") {
      parsed.help = true;
    } else {
      throw new Error(`Unknown argument: ${arg}`);
    }
  }

  const allowed = V1_TARGET_IDS.map((t) => `"${t}"`).join(", ");
  for (const id of parsed.targets) {
    if (!EMIT_TARGETS[id]?.v1) {
      throw new Error(`--target must be one of ${allowed}, got: ${id}`);
    }
  }
  if (parsed.targetFlagGiven && parsed.targets.length === 0) {
    throw new Error(`--target must be one of ${allowed}, got: (empty)`);
  }
  if (parsed.full && parsed.check) {
    throw new Error(
      "--full cannot be combined with --check (--check verifies against the profile recorded in the artifact header)",
    );
  }
  if (parsed.force && parsed.check) {
    throw new Error("--force cannot be combined with --check (--check never writes)");
  }

  // Default target set: all v1 targets (W1 §2, W2 §8 ruling). Explicit
  // targets are deduped and processed in registry order regardless of flag
  // order (determinism, W2 §7.1).
  const requested = parsed.targetFlagGiven ? new Set(parsed.targets) : new Set(V1_TARGET_IDS);
  parsed.targets = V1_TARGET_IDS.filter((id) => requested.has(id));

  return parsed;
}

// W2 §8(b) dual-target advisory — a pure function of the flag set, printed
// only on a no---target emit of both v1 targets; never in artifact bytes.
export const DUAL_TARGET_NOTE = [
  "note: AGENTS.md and CLAUDE.md carry identical payloads. If every tool you run",
  "reads AGENTS.md, emit only it: mind-ontology emit --target agents-md",
].join("\n");

function budgetWarning(build) {
  const contributors = [...build.lineContributions.entries()]
    .filter(([, lines]) => lines > 0)
    .sort(
      (a, b) => b[1] - a[1] || SOURCE_FILES.indexOf(a[0]) - SOURCE_FILES.indexOf(b[0]),
    )
    .slice(0, 3)
    .map(([file, lines]) => `${file} (${lines} lines)`)
    .join(", ");
  return `warning: ${build.target} payload is ${build.payloadLines} lines (soft budget ${PAYLOAD_LINE_BUDGET}); largest contributors: ${contributors}`;
}

/**
 * Write mode (W2 §7.2). Returns { exitCode, stdout, stderr }.
 * Multi-target emits are all-or-nothing: an UNMANAGED refusal writes nothing
 * for any target. Rewriting a fresh artifact is a byte-identical no-op.
 */
export function runEmitWrite(options) {
  validateAgentctxSources(options.cwd);
  const sources = readAgentctx(options.cwd);
  const profile = options.full ? "full" : "default";

  const builds = options.targets.map((target) => buildArtifact({ sources, target, profile }));

  // Refusal scan before any write (W1 §9): an existing headerless file is
  // never silently overwritten and never merged; --force is the only override.
  if (!options.force) {
    for (const build of builds) {
      const path = resolve(options.cwd, build.path);
      if (
        existsSync(path) &&
        parseEmitHeader(canonicalize(readFileSync(path, "utf8"))) === null
      ) {
        throw new Error(
          `Refusing to overwrite ${build.path}: file exists but has no emit header. Move its content into .agentctx/ sources, then re-run with --force to overwrite.`,
        );
      }
    }
  }

  for (const build of builds) {
    const path = resolve(options.cwd, build.path);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, build.artifact, "utf8");
  }

  const warnings = [];
  for (const build of builds) {
    if (build.payloadLines > PAYLOAD_LINE_BUDGET) {
      warnings.push({
        type: "budget-overflow",
        target: build.target,
        payload_lines: build.payloadLines,
        budget: PAYLOAD_LINE_BUDGET,
        message: budgetWarning(build),
      });
    }
  }
  if (!options.targetFlagGiven) {
    warnings.push({ type: "dual-target-note", message: DUAL_TARGET_NOTE });
  }

  let stdout;
  if (options.format === "json") {
    stdout =
      JSON.stringify(
        {
          ok: true,
          written: builds.map((build) => ({
            target: build.target,
            path: build.path,
            profile: build.profile,
            emit_version: EMIT_VERSION,
            source_digest: build.sourceDigest,
            content_digest: build.contentDigest,
            payload_lines: build.payloadLines,
          })),
          warnings: warnings.map(({ message, ...rest }) => rest),
        },
        null,
        2,
      ) + "\n";
  } else {
    stdout =
      builds
        .map(
          (build) =>
            `WROTE  ${build.path}  (${build.target}, profile ${build.profile}, ${build.payloadLines} payload lines)`,
        )
        .join("\n") + "\n";
  }

  const stderr = warnings.map((w) => w.message).join("\n");
  return { exitCode: 0, stdout, stderr: stderr ? `${stderr}\n` : "" };
}

const TEXT_STATUS = {
  ok: "OK",
  missing: "MISSING",
  unmanaged: "UNMANAGED",
  "hand-edited": "HAND-EDITED",
  stale: "STALE",
};

/**
 * Check mode (W1 §8, W2 §7.3-7.4). Writes nothing. A negative verdict is a
 * successful report of a bad state: report on stdout, exit 1. Hard errors
 * (compile failure, usage errors) are thrown and exit 2 in the entry point.
 */
export function runEmitCheck(options) {
  validateAgentctxSources(options.cwd);
  const sources = readAgentctx(options.cwd);

  const results = options.targets.map((target) =>
    classifyTarget({ cwd: options.cwd, target, sources }),
  );
  const drifted = results.filter((r) => r.status !== "ok");
  const ok = drifted.length === 0;

  let stdout;
  if (options.format === "json") {
    stdout =
      JSON.stringify(
        {
          ok,
          targets: results.map((r) => ({
            target: r.target,
            path: r.path,
            status: r.status,
            detail: r.detail,
          })),
        },
        null,
        2,
      ) + "\n";
  } else {
    const lines = results.map((r) =>
      r.status === "ok"
        ? `${TEXT_STATUS.ok.padEnd(13)}${r.path} (${r.target}, profile ${r.profile})`
        : `${TEXT_STATUS[r.status].padEnd(13)}${r.path} (${r.target}) - ${r.detail}`,
    );
    lines.push(
      ok
        ? `OK - ${results.length} of ${results.length} targets fresh`
        : `DRIFT - ${drifted.length} of ${results.length} targets need attention`,
    );
    stdout = lines.join("\n") + "\n";
  }

  return { exitCode: ok ? 0 : 1, stdout, stderr: "" };
}

function printHelp() {
  return `mind-ontology emit — compile static per-tool artifacts from .agentctx/

Usage:
  mind-ontology emit [options]            write all v1 targets (AGENTS.md, CLAUDE.md)
  mind-ontology emit --check [options]    verify freshness; writes nothing

Options:
  --target <id>[,<id>]   Restrict to targets: agents-md, claude-md. Repeatable.
  --check                Classify each target (OK/MISSING/UNMANAGED/HAND-EDITED/STALE).
                         Exit 0 fresh, 1 drift, 2 error.
  --force                Overwrite an existing un-managed file (one without an emit
                         header). Never needed for refreshing managed artifacts.
  --full                 Emit the whole ontology instead of the default profile.
  --format text|json     Output format (default: text).
  --cwd <path>           Project root containing .agentctx/ (default: cwd).
  -h, --help             Show this help message.

Both files carry identical payloads by design; if every tool you run reads
AGENTS.md, emit only it: mind-ontology emit --target agents-md
`;
}

const isMain = process.argv[1] === fileURLToPath(import.meta.url);

if (isMain) {
  // Exit-code contract (W2 §2.4): write mode is 0/1; check mode is the
  // three-way split — 0 fresh, 1 drift, 2 hard error (usage errors and
  // compile failures included, so `1` means exactly "re-emit needed").
  const argv = process.argv.slice(2);
  const checkMode = argv.includes("--check");
  try {
    const options = parseEmitArgv(argv);
    if (options.help) {
      process.stdout.write(printHelp());
      process.exit(0);
    }
    const result = options.check ? runEmitCheck(options) : runEmitWrite(options);
    if (result.stdout) process.stdout.write(result.stdout);
    if (result.stderr) process.stderr.write(result.stderr);
    process.exit(result.exitCode);
  } catch (error) {
    process.stderr.write(`${error.message}\n`);
    process.exit(checkMode ? 2 : 1);
  }
}
