#!/usr/bin/env node

/**
 * mind-ontology setup — per-client adoption wiring (Adoption Autoload v1).
 *
 * Prints (or writes) the small set of pieces a project needs so an AI coding
 * agent reads Mind Ontology context at startup / first action instead of
 * relying on a human to remember the MCP tool:
 *
 *   1. the MCP server config block for the client (a practical helper — wiring
 *      a server does not guarantee every agent run auto-calls it);
 *   2. a startup / first-action bootstrap instruction for the agent, with the
 *      non-generated place it belongs (never the emit-owned artifacts);
 *   3. how the emitted AGENTS.md / CLAUDE.md artifacts relate to the live path;
 *   4. the safe failure mode when `.agentctx/` is missing (fail closed, never
 *      invent context).
 *
 * Determinism invariant: output is a pure function of (target, the presence of
 * the two candidate server paths under --cwd, the presence of .agentctx/).
 * No timestamps, no machine identity, no network or model calls. Generated
 * config content carries only project-relative paths — never an absolute path.
 */

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export const SETUP_VERSION = 1;

// Where the stdio MCP server can live relative to a project root, checked in
// order: the repo-local layout (this repo itself, or a vendored copy) wins
// over an npm-installed dependency. When neither exists the dependency path
// is still emitted (with a warning) so the config is correct after install.
export const SERVER_PATH_CANDIDATES = [
  "scripts/agentctx/mcp-server.mjs",
  "node_modules/mind-ontology/scripts/agentctx/mcp-server.mjs",
];

export function resolveServerPath(cwd) {
  for (const candidate of SERVER_PATH_CANDIDATES) {
    if (existsSync(resolve(cwd, candidate))) {
      return { path: candidate, found: true };
    }
  }
  return { path: SERVER_PATH_CANDIDATES[1], found: false };
}

// The startup / first-action bootstrap instruction, identical across targets:
// the meaning layer is the same no matter which client reads it. The last
// step is the safe failure mode — an agent without the tools or sources must
// say so and fail closed, not improvise project context.
export const BOOTSTRAP_INSTRUCTION = [
  "Mind Ontology bootstrap — startup / first action:",
  "1. At the start of every task, before making changes, call the `agentctx`",
  "   MCP tool `get_context` with the task description.",
  "2. Before destructive or structural changes, call `list_constraints`.",
  "3. If the agentctx tools are unavailable or `.agentctx/` is missing, say so",
  "   and continue without inventing project context; scaffold sources with:",
  "   mind-ontology init",
].join("\n");

function buildMcpJson(serverPath) {
  return (
    JSON.stringify(
      { mcpServers: { agentctx: { command: "node", args: [serverPath] } } },
      null,
      2,
    ) + "\n"
  );
}

function buildCodexToml(serverPath) {
  return [
    "# agentctx MCP server — project-local Codex config.",
    "# Generated by: mind-ontology setup --target codex",
    "# Requires this repo to be a trusted Codex project (see docs/agent-setup.md).",
    "",
    "[mcp_servers.agentctx]",
    'command = "node"',
    `args = ["${serverPath}"]`,
    "",
  ].join("\n");
}

// Per-client registry. `instructionHome` names the NON-generated place the
// bootstrap instruction belongs; the emit-owned artifacts re-emit over hand
// edits, so they are never a paste target. `artifactsNote` states the
// emitted-artifact relationship without overpromising: the emitted file is
// what the client auto-reads at startup, the MCP config is a helper, and the
// bootstrap instruction is what asks the agent to actually call the tools.
export const SETUP_TARGETS = {
  "claude-code": {
    label: "Claude Code",
    configPath: ".mcp.json",
    buildConfig: buildMcpJson,
    instructionHome:
      "Paste into CLAUDE.local.md (per-user) or your Claude Code user memory — " +
      "not into the generated CLAUDE.md; `mind-ontology emit` owns that file " +
      "and re-emits over hand edits.",
    artifactsNote:
      "Claude Code auto-reads the generated CLAUDE.md at startup; keep it fresh " +
      "with `mind-ontology emit` (gate: `emit --check`). The MCP config above is " +
      "a practical helper, not a guarantee that every run auto-calls the server — " +
      "the bootstrap instruction is what asks the agent to read context at " +
      "startup / first action; the live `get_context` path then returns richer, " +
      "task-scoped packs than the static file.",
  },
  codex: {
    label: "Codex",
    configPath: ".codex/config.toml",
    buildConfig: buildCodexToml,
    instructionHome:
      "Paste into your user-level Codex guidance (for example ~/.codex/AGENTS.md) — " +
      "not into the repo's generated AGENTS.md; `mind-ontology emit` owns that " +
      "file and re-emits over hand edits.",
    artifactsNote:
      "Codex auto-reads the generated AGENTS.md at startup; keep it fresh with " +
      "`mind-ontology emit` (gate: `emit --check`). The MCP config above is a " +
      "practical helper, not a guarantee that every run auto-calls the server — " +
      "the bootstrap instruction is what asks the agent to read context at " +
      "startup / first action; the live `get_context` path then returns richer, " +
      "task-scoped packs than the static file.",
  },
};

export const SETUP_TARGET_IDS = Object.keys(SETUP_TARGETS);

function allowedTargets() {
  return SETUP_TARGET_IDS.map((id) => `"${id}"`).join(", ");
}

/**
 * Build the whole setup plan as data — the single source for both output
 * formats and for the write step. Reads only the filesystem facts named in
 * the determinism invariant; never writes.
 */
export function buildSetupPlan({ cwd, target }) {
  const spec = SETUP_TARGETS[target];
  if (!spec) {
    throw new Error(`--target must be one of ${allowedTargets()}, got: ${target}`);
  }

  const server = resolveServerPath(cwd);
  const agentctxPresent = existsSync(resolve(cwd, ".agentctx"));

  const warnings = [];
  if (!server.found) {
    warnings.push(
      `warning: MCP server script not found under the project (looked for ${SERVER_PATH_CANDIDATES.join(", ")}); the config assumes "npm install mind-ontology" will provide it`,
    );
  }
  if (!agentctxPresent) {
    warnings.push(
      "warning: .agentctx/ not found in the project; the MCP server fails closed (no invented context) until you scaffold sources with: mind-ontology init",
    );
  }

  return {
    target,
    label: spec.label,
    configPath: spec.configPath,
    configContent: spec.buildConfig(server.path),
    serverPath: server.path,
    serverFound: server.found,
    agentctxPresent,
    instruction: BOOTSTRAP_INSTRUCTION,
    instructionHome: spec.instructionHome,
    artifactsNote: spec.artifactsNote,
    warnings,
  };
}

export function renderSetupText(plan, { mode }) {
  const action =
    mode === "print"
      ? `PLAN   ${plan.configPath} (${plan.label} MCP config) — printed only, nothing written`
      : `WROTE  ${plan.configPath} (${plan.label} MCP config)`;
  return [
    `mind-ontology setup — ${plan.label}`,
    "",
    action,
    "",
    plan.configContent.trimEnd(),
    "",
    "BOOTSTRAP  startup / first-action instruction (paste where noted below):",
    "",
    plan.instruction,
    "",
    plan.instructionHome,
    "",
    `ARTIFACTS  ${plan.artifactsNote}`,
    "",
  ].join("\n");
}

export function renderSetupJson(plan, { mode }) {
  return (
    JSON.stringify(
      {
        ok: true,
        setup_version: SETUP_VERSION,
        target: plan.target,
        mode,
        config: {
          path: plan.configPath,
          content: plan.configContent,
          server_path: plan.serverPath,
          server_found: plan.serverFound,
          action: mode === "print" ? "printed" : "written",
        },
        bootstrap: {
          instruction: plan.instruction,
          home: plan.instructionHome,
        },
        artifacts_note: plan.artifactsNote,
        agentctx_present: plan.agentctxPresent,
        warnings: plan.warnings,
      },
      null,
      2,
    ) + "\n"
  );
}

/**
 * Execute one setup invocation. Print mode never touches the filesystem.
 * Write mode creates the config file only when absent — an existing file is
 * never overwritten or merged (fail closed; --print gives the block to merge
 * by hand). Returns { exitCode, stdout, stderr }.
 */
export function runSetup(options) {
  const plan = buildSetupPlan({ cwd: options.cwd, target: options.target });
  const mode = options.print ? "print" : "write";

  if (mode === "write") {
    const path = resolve(options.cwd, plan.configPath);
    if (existsSync(path)) {
      throw new Error(
        `Refusing to overwrite ${plan.configPath}: file already exists. Re-run with --print and merge the agentctx server block by hand.`,
      );
    }
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, plan.configContent, "utf8");
  }

  const stdout =
    options.format === "json"
      ? renderSetupJson(plan, { mode })
      : renderSetupText(plan, { mode });
  const stderr = plan.warnings.join("\n");

  return { exitCode: 0, stdout, stderr: stderr ? `${stderr}\n` : "" };
}

export function parseSetupArgv(argv = process.argv.slice(2)) {
  const parsed = {
    target: null,
    print: false,
    format: "text",
    cwd: process.cwd(),
    help: false,
  };

  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--target") {
      parsed.target = argv[++i] ?? "";
    } else if (arg === "--print") {
      parsed.print = true;
    } else if (arg === "--format") {
      const f = argv[++i] ?? "";
      if (f !== "text" && f !== "json") {
        throw new Error(`--format must be "text" or "json", got: ${f}`);
      }
      parsed.format = f;
    } else if (arg === "--cwd") {
      parsed.cwd = resolve(argv[++i] ?? parsed.cwd);
    } else if (arg === "-h" || arg === "--help") {
      parsed.help = true;
    } else {
      throw new Error(`Unknown argument: ${arg}`);
    }
  }

  if (parsed.help) return parsed;
  if (parsed.target === null) {
    throw new Error(
      `Missing required --target argument (allowed: ${allowedTargets()})`,
    );
  }
  if (!SETUP_TARGETS[parsed.target]) {
    throw new Error(
      `--target must be one of ${allowedTargets()}, got: ${parsed.target || "(empty)"}`,
    );
  }
  return parsed;
}

function printHelp() {
  return `mind-ontology setup — wire an AI coding agent to read this ontology at startup

Usage:
  mind-ontology setup --target <client> [options]

Targets:
  claude-code   write/print .mcp.json (project-scope MCP config)
  codex         write/print .codex/config.toml (project-local MCP config)

Options:
  --target <client>      Required. One of: claude-code, codex.
  --print                Print the plan only; write nothing.
  --format text|json     Output format (default: text).
  --cwd <path>           Project root to set up (default: cwd).
  -h, --help             Show this help message.

Without --print the MCP config file is created when absent; an existing file
is never overwritten or merged (use --print and merge by hand). The startup /
first-action bootstrap instruction is always printed — paste it into the
non-generated instruction layer named in the output, never into the emitted
AGENTS.md / CLAUDE.md (those are owned by: mind-ontology emit).
`;
}

const isMain = process.argv[1] === fileURLToPath(import.meta.url);

if (isMain) {
  try {
    const options = parseSetupArgv();
    if (options.help) {
      process.stdout.write(printHelp());
      process.exit(0);
    }
    const result = runSetup(options);
    if (result.stdout) process.stdout.write(result.stdout);
    if (result.stderr) process.stderr.write(result.stderr);
    process.exit(result.exitCode);
  } catch (error) {
    process.stderr.write(`${error.message}\n`);
    process.exit(1);
  }
}
